name: Build SRT-Hunter

on:
  push:
    tags:
      - 'v*'  
  workflow_dispatch: 

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            platform: Windows
          - os: macos-latest
            platform: macOS

    runs-on: ${{ matrix.os }}

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Poetry 설치
        run: pip install poetry

      - name: 버전 정보 추출
        id: get_version
        shell: python
        run: |
          with open('version.py', 'r') as f:
              for line in f:
                  if line.startswith('VERSION ='):
                      version = line.split('=')[1].strip().strip('"')
                      print(f"::set-output name=version::{version}")
                      break

      - name: Windows 빌드
        if: matrix.os == 'windows-latest'
        run: |
          python build-script/build.py

      - name: macOS 빌드
        if: matrix.os == 'macos-latest'
        run: |
          python build-script/build.py

      - name: 빌드 결과물 업로드
        uses: actions/upload-artifact@v3
        with:
          name: SRT-Hunter-${{ steps.get_version.outputs.version }}-${{ matrix.platform }}
          path: dist/SRT-Hunter-v*-${{ matrix.platform }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: 빌드 결과물 다운로드
        uses: actions/download-artifact@v3

      - name: 릴리스 생성
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SRT-Hunter-*-Windows/*.zip
            SRT-Hunter-*-macOS/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 