name: Build SRT-Hunter

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  
  workflow_dispatch: 

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            platform: Windows
          - os: macos-latest
            platform: macOS

    runs-on: ${{ matrix.os }}

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Poetry 설치 (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Poetry 설치 (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: 버전 정보 추출
        id: get_version
        shell: bash
        run: |
          VERSION=$(grep -o 'VERSION = "[^"]*"' version.py | cut -d'"' -f2)
          echo "Version extracted: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 디버그 정보 출력 (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          echo "Version from output: ${{ steps.get_version.outputs.version }}"
          ls -la build-script/

      - name: 디버그 정보 출력 (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          echo "Version from output: ${{ steps.get_version.outputs.version }}"
          Get-ChildItem -Path build-script

      - name: Windows 빌드
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          echo 빌드 스크립트 실행 전 환경 확인:
          cd
          dir build-script
          build-script\build_windows.bat

      - name: macOS 빌드
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          pwd
          ls -la build-script
          chmod +x build-script/build_macos.sh
          bash build-script/build_macos.sh

      - name: 빌드 결과물 업로드
        uses: actions/upload-artifact@v4
        with:
          name: SRT-Hunter-${{ steps.get_version.outputs.version }}-${{ matrix.platform }}
          path: |
            dist/SRT-Hunter-v*-${{ matrix.platform }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: 빌드 결과물 다운로드
        uses: actions/download-artifact@v4

      - name: 릴리스 생성
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SRT-Hunter-*-Windows/*.zip
            SRT-Hunter-*-macOS/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 